export const LOGIN = 'LOGIN_USER';
export const LOGOUT = 'LOGOUT_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// Errors
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const DELETE_ACCOUNT_ERROR = 'DELETE_ACCOUNT_ERROR';