export const FETCH_CONFIGS = 'FETCH_CONFIGS';
export const FETCH_CONFIG = 'FETCH_CONFIG';
export const CREATE_CONFIG = 'CREATE_CONFIG';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';
export const DELETE_CONFIG = 'DELETE_CONFIG';