export const FETCH_MARAUDES = 'FETCH_MARAUDES';
export const FETCH_MARAUDE = 'FETCH_MARAUDE';
export const CREATE_MARAUDE = 'CREATE_MARAUDE';
export const UPDATE_MARAUDE = 'UPDATE_MARAUDE';
export const DELETE_MARAUDE = 'DELETE_MARAUDE';


// Errors
export const ERROR_ON_MARAUDES = 'ERROR_ON_MARAUDES';
export const ERROR_ON_MARAUDE = 'ERROR_ON_MARAUDE';
export const ERROR_ON_CREATE_MARAUDE = 'ERROR_ON_CREATE_MARAUDE';
export const ERROR_ON_UPDATE_MARAUDE = 'ERROR_ON_UPDATE_MARAUDE';
export const ERROR_ON_DELETE_MARAUDE = 'ERROR_ON_DELETE_MARAUDE';