export const FETCH_PARTICIPANTS = 'FETCH_PARTICIPANTS';
export const FETCH_PARTICIPANT = 'FETCH_PARTICIPANT';
export const CREATE_PARTICIPANT = 'CREATE_PARTICIPANT';
// Errors
export const ERROR_ON_PARTICIPANTS = 'ERROR_ON_PARTICIPANTS';
export const ERROR_ON_PARTICIPANT = 'ERROR_ON_PARTICIPANT';
export const ERROR_ON_CREATE_PARTICIPANT = 'ERROR_ON_CREATE_PARTICIPANT';
